apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: k8s-auth
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: k8s-auth
  namespace: k8s-auth
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k8s-auth
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: k8s-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-auth
subjects:
- kind: ServiceAccount
  name: k8s-auth
  namespace: k8s-auth

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-auth
  name: k8s-auth
  namespace: k8s-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-auth
    spec:
      serviceAccountName: k8s-auth
      containers:
      - image: mohamedrafraf/auth-k8s-kube
        name: k8s-auth-kube
        env:
          - name: CLUSTER_NAME
            value: ctf-cluster
          - name: TOKEN
            value: "auOOX3Hg-j6FY2RiITTj"
          - name: SERVER
            value: "server"
          - name: API_SERVER
            value: "api server"
        resources: {}

status: {}



